# html lang
language: en

# main menu navigation
menu:
  Home: /
  Case Studies: /case-studies
  Blog: /blog

# stylesheets loaded in the <head>
stylesheets:
  - /css/begin theme.css

# scripts loaded in the end of the body
scripts:
  - /js/begin theme.js
