# html lang
language: en

# main menu navigation
menu:
  Home: https://beg.in
  Blog: /
  Case Studies: https://beg.in/case-studies

# stylesheets loaded in the <head>
stylesheets:
  - /css/begin-theme.css

# scripts loaded in the end of the body
scripts:
  - /js/begin-theme.js
